<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecturaltemplates" nsURI="http://palladiosimulator.org/ArchitecturalTemplates/1.0"
    nsPrefix="org.palladiosimulator.architecturaltemplates">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="AT" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An AT is a template representing and documenting reusable architectural knowledge. Software architects can apply ATs for both architectural modeling and architectural analyses while AT engineers specify ATs. An optional default AT instance provides software architects with an initial architectural model corresponding to the represented architectural knowledge, e.g., a reference architecture.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalog" lowerBound="1"
        eType="#//Catalog" eOpposite="#//Catalog/ATs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true" eOpposite="#//Role/AT"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationRuleFolder"
        eType="#//ReconfigurationFolder" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A template can provide reconfigurations&#xA;to be applied during analyses."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultInstanceURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="AT constraints specify what software architects are forbidden to change in a software architecture. Such restrictions prescribe software architects possible design decisions, which can ensure that architectural design remains sound. AT constraints can, thus, formalize reusable architectural knowledge applied to an architectural model. These constraints can then ensure the conformance to the architectural knowledge by prohibiting design decisions that would violate conformance."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        eOpposite="#//Role/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Catalog" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Allows to collect Architectural Templates within a catalog."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ATs" upperBound="-1" eType="#//AT"
        containment="true" eOpposite="#//AT/catalog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The responsibilities of an&#xA;architectural element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AT" lowerBound="1" eType="#//AT"
        eOpposite="#//AT/roles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.modelversioning.emfprofile/model/emfprofiles.ecore#//Stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="completion" eType="#//Completion"
        containment="true" eOpposite="#//Completion/role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true" eOpposite="#//Constraint/role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superRoles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OCLConstraint" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="QVTOCompletion" eSuperTypes="#//Completion">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A completion realized as&#xA;QVT Operational transformation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Completion" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A completion is a refinement transformation&#xA;from AT-annotated model into a model with&#xA;well-defined semantics (thus, specifying the&#xA;semantics of a given AT). This particularly&#xA;includes a refinement transformation to another&#xA;AT-annotated model as well (the second AT also&#xA;includes a completion for defining its semantics,&#xA;thus, has well-defined semantics).&#xA; &#xA;As an example, consider a component annotated&#xA;with an AT role &quot;3-times loabalanced&quot;. A completion&#xA;could refine this component into a model with 4&#xA;components: 1 loadbalancer plus 3 replica of the&#xA;originally annotated component. The loadbalancer&#xA;then evenly distributes load over the 3 replica."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//CompletionParameter" containment="true" eOpposite="#//CompletionParameter/completion">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Every in- and output parameter&#xA;of a completion has to exactly&#xA;match this order."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        eOpposite="#//Role/completion">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In addition to constraints, role semantics are defined by a completion."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completionFileURI" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionParameter" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Completion parameters characterize the&#xA;signatures of completions (i.e., the in- and&#xA;output parameters of transformations)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="completion" lowerBound="1"
        eType="#//Completion" eOpposite="#//Completion/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMBlackboardCompletionParameter" eSuperTypes="#//PCMCompletionParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The input of a completion stems from&#xA;the MDSD blackboard and is a PCM&#xA;model, characterized by its typical file&#xA;extension. The user can select from&#xA;available PCM extensions."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PCMFileExtensions">
    <eLiterals name="SYSTEM" literal="system"/>
    <eLiterals name="ALLOCATION" value="1" literal="allocation"/>
    <eLiterals name="RESOURCEENVIRONMENT" value="2" literal="resourceenvironment"/>
    <eLiterals name="REPOSITORY" value="3" literal="repository"/>
    <eLiterals name="USAGEMODEL" value="4" literal="usagemodel"/>
    <eLiterals name="RESOURCETYPE" value="5" literal="resourcetype"/>
    <eLiterals name="MONITORREPOSITORY" value="6" literal="monitorrepository"/>
    <eLiterals name="PCMMEASURINGPOINT" value="7" literal="pcmmeasuringpoint"/>
    <eLiterals name="SERVICELEVELOBJECTIVE" value="8" literal="slo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMTemplateCompletionParameter" eSuperTypes="#//PCMCompletionParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The input of a completion is a PCM&#xA;model from a template and available&#xA;via the MDSD blackboard within the&#xA;PCM partition."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateFileURI" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMOutputCompletionParameter" eSuperTypes="#//PCMCompletionParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The output of a completion is a PCM model,&#xA;characterized by its typical file extension. A&#xA;user can select from available PCM extensions."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationFolder">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A folder with self-adaptation rules."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderURI" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsolatedPCMTemplateCompletionParameter"
      eSuperTypes="#//PCMTemplateCompletionParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The input of a completion is a PCM model&#xA;from a template and available via the&#xA;MDSD blackboard within a partition isolated&#xA;from the main PCM partition."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMCompletionParameter" abstract="true"
      eSuperTypes="#//CompletionParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileExtension" lowerBound="1"
        eType="#//FileExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileExtension" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCMFileExtension" eSuperTypes="#//FileExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
        eType="#//PCMFileExtensions" defaultValueLiteral="system"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericFileExtension" eSuperTypes="#//FileExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
